language: php

php:
  - 7.4
  - 8.0

sudo: false

env:
  global:
    - SYMFONY_VERSION=""

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: SYMFONY_VERSION=5.1.*
    - php: 7.4
      env: SYMFONY_VERSION=5.2.*
    - php: 8.0
      env: SYMFONY_VERSION=4.4.*
    - php: 8.0
      env: SYMFONY_VERSION=5.1.*
    - php: 8.0
      env: SYMFONY_VERSION=5.2.*

before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

before_install:
  - if [[ "$SYMFONY_VERSION" != "" ]]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

script: phpunit

notifications:
  email:
    - sven.loth@me.com
